### ISSUE TITLE
flex 自动布局是如何计算的？

### ISSUE THREAD

**Issue by Jouryjc** [Jouryjc/blog#44]
基础知识这里不打算讲。随便一篇介绍 flex 的[博客](<http://www.ruanyifeng.com/blog/2015/07/flex-grammar.html>)看了之后都能学会它的用法。

我重点说说 `flex-basis`、`flex-shrink`、`flex-grow`的算法。

#### flex-basis

指定了 `flex` 元素在主轴方向上的初始大小。默认值是 `auto`，关于 auto 这个属性值 [MDN](<https://developer.mozilla.org/zh-CN/docs/Web/CSS/flex-basis>) 上还有一段简史，可以了解了解。废话不多说，直接上:chestnut:

```html
<div class="container">
  <div class="item one">200px</div>
  <div class="item two">500px</div>
</div>
```

```css
.container {
  display: flex;
  width: 1000px;
  height: 50px;
  background-color: green;
}
.item {
  flex-basis: auto;
  height: 100%;
  text-align: center;
  line-height: 50px;
}
.one {
  width: 200px;
  background-color: red;
}
.two {
  width: 500px;
  background-color: orange;
}
```
<img width="1006" alt="WX20190424-201645@2x" src="https://user-images.githubusercontent.com/11925053/56743533-5124a200-67a9-11e9-8e5a-b2bb5861af13.png">

可以看到，`auto` 就是满足 `width:auto` 的宽度。flex: 0 会是什么效果呢？
<img width="1001" alt="WX20190424-202456@2x" src="https://user-images.githubusercontent.com/11925053/56743627-816c4080-67a9-11e9-9fdd-8d0fbab8e95d.png">

可以看到，子元素的 `width` 都失效了。其实它是子元素的最小宽度。将 `500px` 替换成一个 DOM：

```html
<div class="item two">
  <div class="two-child">400px</div>
</div>
```

```css
.two-child {
  width: 400px；
}
```

结果如下图所示：
<img width="1004" alt="WX20190424-204007@2x" src="https://user-images.githubusercontent.com/11925053/56743643-8b8e3f00-67a9-11e9-81d3-f0afa9863fd4.png">

#### flex-grow

回到最初 `200px`、 `500px` 的例子，`200 + 500 = 700` 并没有完全撑满整个父元素 `.container` 的宽度，剩余的宽度是如何处理的呢？答案是通过 `flex-grow` 属性去设置的：

```css
.one {
  flex-grow: 1;
}
.two {
  flex-grow: 1;
}
```

通过上述样式，就可以将剩余的 `300px` 平均分给` .one .two `元素。

<img width="1004" alt="WX20190424-205440@2x" src="https://user-images.githubusercontent.com/11925053/56743658-934de380-67a9-11e9-9eaf-e28af1512f00.png">

如果结合下面样式会是怎样的呢？

```css
.item {
  flex-basis: 0%;
}
```

答案是 `.one .two` 平分`1000px`，即各 `500px`。不受子元素的影响。

<img width="1008" alt="WX20190424-210237@2x" src="https://user-images.githubusercontent.com/11925053/56743673-9ba61e80-67a9-11e9-8739-cdf4abe4dd5f.png">

#### flex-shrink

父元素宽度不够时就要压缩子元素的宽度，通过 flex-shrink  配置。缩小不比扩大那么简单，缩小的计算方法会复杂一些。还是用最前面的例子：

```css
.one {
  width: 600px;
  flex-shrink: 1;
}
.two {
  width: 800px;
  flex-shrink: 1;
}
```

按照自动放大的方式，应该是 `(600+800-1000)/2`, `.one` 应该是 `400px`，`.two` 应该是` 600px`：

<img width="1009" alt="WX20190424-211401@2x" src="https://user-images.githubusercontent.com/11925053/56743699-a6f94a00-67a9-11e9-98b9-5d0fb70552e5.png">

结果 `.one` 是 `428.58px`，这是如何计算过来的呢？

```js
.one = (600 * 1/(600*1 + 800*1))*1000 ≈ 428.58
.two = (800 * 1/(600*1 + 800*1))*1000 ≈ 571.42
```

我们换一个比例来验证一下想法：

```cs
.one {
  width: 600px;
  flex-shrink: 2;
}
.two {
  width: 800px;
  flex-shrink: 3;
}
```

通过计算我们得到：

```js
.one = (600*2/(600*2 + 800*3))*400 ≈ 133.33
.two = (800*3/(600*2 + 800*3))*400 ≈ 266.67
```

所以 `.one` 的宽度是 600 - 133.33 px， `.two` 的宽度是 800 - 266.67 px。下面验证一下结果：

<img width="1013" alt="屏幕快照 2019-04-25 22 24 18" src="https://user-images.githubusercontent.com/11925053/56743719-b5476600-67a9-11e9-8dd9-f9079d151d5a.png">
<img width="1008" alt="屏幕快照 2019-04-25 22 25 27" src="https://user-images.githubusercontent.com/11925053/56743723-b8daed00-67a9-11e9-82fb-e67370a20e53.png">

Bingo！正如我们的猜想那样。
